### ISSUE TITLE
Client can't handle certificate from api.fidesmo.com

### ISSUE THREAD

**Issue by luisrodero-fidesmo** [fidesmo/mifare-tutorial#8]
(Task defined in [Open Project WP #126](https://fidesmo.openproject.com/projects/development-focus/work_packages/126/activity))

This error is shown:
```
2018-01-11T17:40:33.307220+00:00 app[web.1]: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
2018-01-11T17:40:33.333191+00:00 app[web.1]: 	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
2018-01-11T17:40:33.333389+00:00 app[web.1]: 	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1904)
2018-01-11T17:40:33.333480+00:00 app[web.1]: 	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:279)
2018-01-11T17:40:33.333561+00:00 app[web.1]: 	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:273)
2018-01-11T17:40:33.333630+00:00 app[web.1]: 	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1446)
2018-01-11T17:40:33.333705+00:00 app[web.1]: 	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:209)
2018-01-11T17:40:33.333934+00:00 app[web.1]: 	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:901)
2018-01-11T17:40:33.334027+00:00 app[web.1]: 	at sun.security.ssl.Handshaker.process_record(Handshaker.java:837)
2018-01-11T17:40:33.334087+00:00 app[web.1]: 	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1023)
2018-01-11T17:40:33.334193+00:00 app[web.1]: 	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1332)
2018-01-11T17:40:33.334275+00:00 app[web.1]: 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1359)
2018-01-11T17:40:33.334336+00:00 app[web.1]: 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1343)
2018-01-11T17:40:33.334413+00:00 app[web.1]: 	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563)
2018-01-11T17:40:33.334467+00:00 app[web.1]: 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
2018-01-11T17:40:33.334544+00:00 app[web.1]: 	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1092)
2018-01-11T17:40:33.334650+00:00 app[web.1]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:250)
2018-01-11T17:40:33.334698+00:00 app[web.1]: 	at com.fidesmo.mifaretutorial.MifareRobot.sendOperationAndProcessResponse(MifareRobot.java:126)
2018-01-11T17:40:33.334781+00:00 app[web.1]: 	at com.fidesmo.mifaretutorial.MifareRobot.getCard(MifareRobot.java:28)
(...)
```

Seemingly such errors are due to certificates that cannot be verified by the client.

**Comment by Franzaine** [comment]
@luisrodero-fidesmo this might be related: https://github.com/fidesmo/android-sec-client/pull/755

**Comment by luisrodero-fidesmo** [comment]
Thanks @Franzaine ! I'll check that.

**Comment by luisrodero-fidesmo** [comment]
That made the trick. But now the phone app gets stuck when calling the 'invoke' service. When requested the phone shows the 'put the card behind the phone' message, after the user does that it shows the 'wait for a while' message. And that's all. The client app is stuck there and no more activity is seen in the SP logs either. I'll research that.
